config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :courses do
    get '/activate', to: 'courses#activate'
    get '/deactivate', to: 'courses#deactivate'
  end
  resources :students do
    get '/activate', to: 'students#activate'
    get '/deactivate', to: 'students#deactivate'
  end
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  belongs_to :student
  belongs_to :course
  before_create :set_entry_at

  def set_entry_at
    self.entry_at = DateTime.now
  end
end

app/models/concerns/shared_methods.rb
module SharedMethods
  def set_status
    self.status = 1
  end

  def activate
    self.status = 1
  end

  def deactivate
    self.status = 0
  end

  def active?
    return 'Yes' if self.status == 1
    'No'
  end
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :students, through: :classrooms
  has_many :classrooms
  validates :name, presence: true
  before_create :set_status
  include SharedMethods
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :courses, through: :classrooms
  has_many :classrooms
  validates :name, presence: true
  before_create :set_status
  include SharedMethods

  def register_number
    self.id.to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  def deactivate
    course = Course.find(params[:course_id])
    course.deactivate
    course.save
    redirect_to :back
  end

  def activate
    course = Course.find(params[:course_id])
    course.activate
    course.save
    redirect_to :back
  end

  def index
    @courses = Course.all
  end

  def show
  end

  def new
    @course = Course.new
  end

  def edit
  end

  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :description, { :student_ids => [] })
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  def deactivate
    student = Student.find(params[:student_id])
    student.deactivate
    student.save
    redirect_to :back
  end

  def activate
    student = Student.find(params[:student_id])
    student.activate
    student.save
    redirect_to :back
  end

  def index
    @students = Student.all
  end

  def show
  end

  def new
    @student = Student.new
  end

  def edit
  end

  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit([:name, { :course_ids => [] }])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/courses/_form.html.haml
= form_for @course, html: { class: "form form-horizontal course" } do |f|
  .form-group
    = f.label :name, class: 'control-label'
    .controls
      = f.text_field :name, class: 'form-control', required: true
    = error_span(@course[:name])
  .form-group
    = f.label :description, class: 'control-label'
    .controls
      = f.text_field :description, class: 'form-control', required: true
    = error_span(@course[:description])
  #h3 Students
  #students
    %span.ul
      - Student.all.each do |student|
        %label.li
          = check_box_tag :student_ids, student.id, @course.students.include?(student), :name => 'course[student_ids][]'
          = student.name
  = f.submit nil,class: 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), courses_path, :class => 'btn btn-default'

app/views/courses/edit.html.haml
- model_class = Course
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/courses/index.html.haml
- model_class = Course
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:description)
      %th= 'Active'
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @courses.each do |course|
      %tr
        %td= link_to course.name, course_path(course)
        %td= course.description
        %td= course.active?
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_course_path(course), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), course_path(course), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_course_path, :class => 'btn btn-primary'

app/views/courses/new.html.haml
- model_class = Course
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/courses/show.html.haml
- model_class = Course
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @course.name
%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @course.description
%p
  %strong= 'Active:'
  %br
  = @course.active?
%div#students
  %h3 Students:
  - @course.students.each do |student|
    %p
      = link_to student.name, student_path(student)

= link_to t('.back', :default => t("helpers.links.back")), courses_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_course_path(@course), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), course_path(@course), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'
- if @course.active? == 'Yes'
  = link_to t('.edit', :default => 'Deactivate'), course_deactivate_path(@course), :class => 'btn btn-default'
- else
  = link_to t('.edit', :default => 'Activate!'), course_activate_path(@course), :class => 'btn btn-default'

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Academic"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand(href="/") Academic
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            %li= link_to "Students", students_path
            %li= link_to "Courses", courses_path

    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield

app/views/pages/home.html.haml
%h1
  Academic System

app/views/students/_form.html.haml
= form_for @student, html: { class: "form form-horizontal student" } do |f|
  .form-group
    = f.label :name, class: 'control-label'
    .controls
      = f.text_field :name, class: 'form-control', required: true
    = error_span(@student[:name])
  #h3 Courses
  #courses
    %span.ul
      - Course.all.each do |course|
        %label.li
          = check_box_tag :course_ids, course.id, @student.courses.include?(course), :name => 'student[course_ids][]'
          = course.name
  = f.submit nil,class: 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), students_path, :class => 'btn btn-default'

app/views/students/edit.html.haml
- model_class = Student
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/students/index.html.haml
- model_class = Student
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:register_number)
      %th= 'Active'
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @students.each do |student|
      %tr
        %td= link_to student.name, student_path(student)
        %td= student.register_number
        %td= student.active?
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_student_path(student), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), student_path(student), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_student_path, :class => 'btn btn-primary'

app/views/students/new.html.haml
- model_class = Student
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/students/show.html.haml
- model_class = Student
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @student.name
%p
  %strong= model_class.human_attribute_name(:register_number) + ':'
  %br
  = @student.register_number
%p
  %strong= 'Active:'
  %br
  = @student.active?
%div#courses
  %h3 Courses:
  - @student.courses.each do |course|
    %p
      = link_to course.name, course_path(course)


= link_to t('.back', :default => t("helpers.links.back")), students_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_student_path(@student), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), student_path(@student), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'
- if @student.active? == 'Yes'
  = link_to t('.edit', :default => 'Deactivate'), student_deactivate_path(@student), :class => 'btn btn-default'
- else
  = link_to t('.edit', :default => 'Activate!'), student_activate_path(@student), :class => 'btn btn-default'